services:
  - type: web
    name: college-predictor-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
